### ISSUE TITLE
Forge client not able to connect to (K)Cauldron server behind Waterfall

### ISSUE THREAD

**Issue by NullOrNaN** [WaterfallMC/Waterfall-Old#11]
It seems that, like normal Bungee, there's an issue with clients connecting to Cauldron/KCauldron  server's behind the proxy. I was told by TechCable in his channel to submit an issue if this doesn't work as I expected it not to work myself.

[Pastebined error](https://pastebin.com/3JhhjGGJ)

**Comment by dualspiral** [comment]
https://github.com/SpigotMC/BungeeCord/pull/1452

This was an original PR that fix this problem, though I suggest the maintainers consider whether there is a better way to do this. Might not be, of course...

**Comment by Techcable** [comment]
I think we should fix this.
Do negative packets crash vanilla minecraft?

**Comment by dualspiral** [comment]
Any packet ID that isn't in vanilla will crash vanilla minecraft. However, they shouldn't be sent by the Forge mod unless the mod knows the client can accept them.

**Comment by Techcable** [comment]
I have no way to confirm this works, so please test.

**Comment by dualspiral** [comment]
No, you haven't fixed this. It'll crash here.

https://github.com/WaterfallMC/Waterfall/blob/master/proxy/src/main/java/net/md_5/bungee/entitymap/EntityMap.java#L107

**Comment by NullOrNaN** [comment]
This is indeed not resolved. [Pastebin of new log](https://pastebin.com/KQgRyAsC)

**Comment by Techcable** [comment]
Once again, I can't test this, so just tell me if it doesn't work.
I think that's the same exception @MatthewM but there isn't any stack trace for me to be sure.

**Comment by MatthewM** [comment]
@Techcable the same exact issue appears to be present. It's the same error too.

**Comment by Techcable** [comment]
Whoops, I think i deleted your message @MatthewM 
I feel stupid.

What mods are you using?

Anyways, there is no option for me too print stack traces, and it wouldn't help that much.
I probably have to either try again, or actually test with the mods.

**Comment by NullOrNaN** [comment]
I did a bit of research for you! It's seemingly some CoFH mods that's causing the issues. Sadly, CoFH mods are very popular..

There's a [closed issue](https://github.com/SpigotMC/BungeeCord/issues/1437) on Bungeecord's tracker.

Basically you need to install KCauldron (think mine is 1.7.10-1614 currently), CoFHCore and some other CoFH Mods. Here's my full and current[ client-side mod list](http://www.technicpack.net/modpack/flux-world.761995/mods).

**Comment by NullOrNaN** [comment]
Actually Yive had merged some patches previously in [another bungee fork](https://github.com/TCPR/BungeeCord) that's not kept updated and was done as a one off. Maybe take a look?

**Comment by Techcable** [comment]
@MatthewM 
Thanks for the info.
The reason this has been so difficult is because im trying to only allow negative ids to forge servers.

Maybe @minecrafter could consider passing throuh negative packets to all servers?
I'll PR a fix to PaperSpigot for the negative ids if so.

**Comment by NullOrNaN** [comment]
@Techcable @minecrafter The problem with TCPR's repo is it is outdated. Not that it doesn't properly handle it with 1.8 vanilla clients, Spigot servers, and Forge Client/Servers

Here's a [diff](https://github.com/WaterfallMC/Waterfall/compare/master...TCPR:master) between you and them.

**Comment by Techcable** [comment]
And @minecrafter said he wanted it to block negative packets to vanilla servers.

**Comment by dualspiral** [comment]
@minecrafter @Techcable 

The only times when negative ID packets (or indeed, any non-Vanilla packets) should be sent is when both the Forge client and server have the same mod installed (CoFH Core, for example), so the client should always be expecting the packet, and vice versa. If a mod wants to send a negative ID packet and the client isn't aware, it'll crash the client if Waterfall isn't there, all you are doing by trying to work about it is make Waterfall throw an exception instead of the client, and inherently you're then putting the blame on yourselves and making things way harder for server admins to diagnose (blaming the wrong component, Waterfall) and the mod authors to solve.

You're making this way too hard by trying to solve a problem that doesn't exist in the first place, or at least isn't yours to solve. Just make it so that you pass through all packets, if a mod sends an incorrect packet ID, then it's the mod's problem to solve.

As I suggested above - this is the diff you want: https://github.com/SpigotMC/BungeeCord/pull/1452/files

**Comment by Techcable** [comment]
Un-fixed by 4276513bfb668796b09458ea0c2c3bed3cdc5821
Here's the error: https://gist.github.com/MatthewM/a0c7d395a7163ae8fa92

**Comment by Techcable** [comment]
Re-fixed by 312b3a7ce743145c46aff043b24d84ebdb8c5038
Confirmed by @MatthewM
